spring.application.name=cinehub

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

jwt.secretKey=${JWT_SECRET_KEY}

supabase.url=${SUPABASE_URL}
supabase.api-key=${SUPABASE_API_KEY}
supabase.bucket=movie-posters

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL}
spring.mail.password=${APP_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never