spring.application.name=cinehub


spring.datasource.url=jdbc:postgresql://localhost:5432/Cinehub
spring.datasource.username=postgres
spring.datasource.password=${DBPass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=truespring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true


jwt.secretKey=${JWT_SECRET_KEY}
JWT_SECRET_KEY=mySuperSecretKeyThatIsVeryLongForHS256