spring.application.name=cinehub


driver-class-name: org.postgresql.Driver
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=truespring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true


jwt.secretKey=${JWT_SECRET_KEY}

supabase.url=${SUPABASE_URL}
supabase.api-key=${SUPABASE_API_KEY}
supabase.bucket=movie-posters

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

